version: "3.9"

services:
  postgres:
    container_name: postgres_typeorm_basesource
    image: postgres:15.7
    restart: unless-stopped
    ports:
      - "5440:5432"
    env_file:
      - .docker.env
    volumes:
      - ./.docker-data/postgres/data:/var/lib/postgresql/data
    networks:
      - main-network

  redis:
    container_name: redis_typeorm_basesource
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/redis/data/redis:/data
    networks:
      - main-network
    restart: unless-stopped

  backend:
    container_name: backend_typeorm_basesource
    build:
      context: ./main
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .docker.env
    depends_on:
      - postgres
      - redis
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
